# CalendarioReino Project Documentation
# MkDocs Material Configuration with PRINCE2 Standards

site_name: CalendarioReino Project Documentation
site_description: Comprehensive project documentation for the CalendarioReino Salesforce Lightning Web Component
site_author: Reino Capital
site_url: https://joaolucaswork.github.io/fa-calendar-docs

# Repository
repo_name: fa-calendar-docs
repo_url: https://github.com/joaolucaswork/fa-calendar-docs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Reino Capital

# Configuration
theme:
  name: material
  language: en
  
  # Theme features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  # Color palette
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Fonts
  font:
    text: Roboto
    code: Roboto Mono

  # Icons
  icon:
    logo: material/calendar-clock
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      enable_git_follow: false
  # - git-committers:
  #     repository: joaolucaswork/fa-calendar-docs
  #     branch: main
  - tags
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'light'
      javascript: https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

# Customization
extra:
  status:
    new: Recently added
    deprecated: Deprecated
    
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joaolucaswork/fa-calendar-docs
    - icon: fontawesome/brands/linkedin
      link: https://br.linkedin.com/in/gabriel-tintori-276b93105
      
  alternate:
    - name: English
      link: /
      lang: en
    - name: Português
      link: /pt/
      lang: pt

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: joaolucaswork
      repo: fa-calendar-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Quick Start: getting-started/quick-start.md
  - Project Overview:
    - project-overview/index.md
    - Project Charter: project-overview/charter.md
  - Business Case: business-case/index.md
  - Architecture: architecture/index.md
  - Quality: quality/index.md
  - Risk Management: risk-management/index.md
  - Technical: 
    - technical/index.md
    - Features: technical/features.md

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css
  - stylesheets/prince2.css

extra_javascript:
  - javascripts/extra.js
